{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tgo.rtc",
    "module": "tgortc",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tgortc-1.0.0.aar",
          "url": "tgortc-1.0.0.aar",
          "size": 80457,
          "sha512": "ff27dc097028f46ce9d61cb7e191d17415008c4f8a8c61e6901cc5a3c9d21c0cc74f43f3820c4aeb35c1507531e348e8a0bfa45221a9046c85ce1445174695d1",
          "sha256": "137da8f7af7aa8552d03348ced08e5b1a52f4d91e9fc307c87259ebf63f12ef4",
          "sha1": "93a6bc2cc293e94c514ccddc9590ed0f9cb482be",
          "md5": "f59a84bf3ae74b17453576f923a00993"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tgortc-1.0.0.aar",
          "url": "tgortc-1.0.0.aar",
          "size": 80457,
          "sha512": "ff27dc097028f46ce9d61cb7e191d17415008c4f8a8c61e6901cc5a3c9d21c0cc74f43f3820c4aeb35c1507531e348e8a0bfa45221a9046c85ce1445174695d1",
          "sha256": "137da8f7af7aa8552d03348ced08e5b1a52f4d91e9fc307c87259ebf63f12ef4",
          "sha1": "93a6bc2cc293e94c514ccddc9590ed0f9cb482be",
          "md5": "f59a84bf3ae74b17453576f923a00993"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "tgortc-1.0.0-sources.jar",
          "url": "tgortc-1.0.0-sources.jar",
          "size": 47478,
          "sha512": "27b645a4434b09bd9f064ed4adb08dca5d4ec5899eb22cdd77222e0dbaf0bc871f83714f9080ae9e1ca11fe5be9a1d9031361b21f7ab88411b79c32cc711b8e5",
          "sha256": "2a589b0ae9a92516445b56562cd0e0aa6aad52885a127635b9d43719ff4144b8",
          "sha1": "3cb836dfa2d8c93e935de0490fc416cc7cef0705",
          "md5": "cabb99753f9dbf2034dc69b64924e112"
        }
      ]
    }
  ]
}
