{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tgo.rtc",
    "module": "tgortc",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tgortc-1.0.0.aar",
          "url": "tgortc-1.0.0.aar",
          "size": 80491,
          "sha512": "4f7927fb2977bdbcb716bd242338861f6adc1090bfa84b8eddf9cd16c85334083a989da4ef332c647925d33e264e184359ac6193ba07b5d52fc24cb59b8f2fe1",
          "sha256": "e4559790bfc0f50685c53a329b212f2fa799a6a2fabe32d73d1cf87857c0970a",
          "sha1": "73fdde557999368600e8d6878159e89f6b06bff3",
          "md5": "9b5a1e3b3b617709333595d0c59d08f3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "io.livekit",
          "module": "livekit-android",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tgortc-1.0.0.aar",
          "url": "tgortc-1.0.0.aar",
          "size": 80491,
          "sha512": "4f7927fb2977bdbcb716bd242338861f6adc1090bfa84b8eddf9cd16c85334083a989da4ef332c647925d33e264e184359ac6193ba07b5d52fc24cb59b8f2fe1",
          "sha256": "e4559790bfc0f50685c53a329b212f2fa799a6a2fabe32d73d1cf87857c0970a",
          "sha1": "73fdde557999368600e8d6878159e89f6b06bff3",
          "md5": "9b5a1e3b3b617709333595d0c59d08f3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "tgortc-1.0.0-sources.jar",
          "url": "tgortc-1.0.0-sources.jar",
          "size": 47520,
          "sha512": "331d9cf4c3abecc3be4df42a319460eeabdd43480ba4ea63e415b1ec3690a7b65cc255993231f3c857e673803494d6e5c20478c689c0c3ed00ef7587b08be0da",
          "sha256": "ed2b4ddb6303f2adaffa67e5ea93af1506d47e560b07882d059dc9a94cc87840",
          "sha1": "989ae53dd1bb6e7f498557381adc6858d8f0d11c",
          "md5": "8041d5d878275d7226ac7fd0cf30119b"
        }
      ]
    }
  ]
}
